spring:
  profiles:
    active:
      - dev

---    
spring:
  profiles: dev
  application:
    name: microservice-springcloud-config-client
server:
  port: 8201
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/
---
spring:
  profiles: test
  application:
    name: microservice-springcloud-config-test
server:
  port: 8202
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka/