spring:
  profiles:
    active: dev,myapp,test
    
spring:
  profiles: dev
  application:
    name: microservice-springcloud-config-dev

spring:
  profiles: test
  application:
    name: microservice-springcloud-config-test 